### ISSUE TITLE
ReferenceError: Can't find variable: _Bytes_read_bytes

### ISSUE THREAD

**Issue by norpan** [elm/bytes#4]
Looks like it may just be spelled `_Bytes_read_Bytes` in the kernel code.
Also, the implementation looks strange, the documentation says:

"Copy a given number of bytes into a new Bytes sequence."

But the kernel code looks like it's trying to read an initial length word, ignoring the length provided.

```
module Main exposing (main)

import Bytes exposing (Endianness(..))
import Bytes.Decode as BD
import Bytes.Encode as BE
import Html


main =
    Html.text (Debug.toString firstByte)


fourBytes =
    BE.encode (BE.unsignedInt32 BE 0xFF995511)


firstByte =
    BD.decode (BD.bytes 1) fourBytes
```

**Comment by evancz** [comment]
Thanks for the report! These things should be fixed in 1.0.2. Let me know if you run into anything else!
