### ISSUE TITLE
Issue with Decoder.bytes: References previous DataView buffer (instead of copying it)

### ISSUE THREAD

**Issue by icidasset** [elm/bytes#8]
~In certain situations, `Decode.loop` uses the state from the previous run.~
Update: The issue seems to be with `Decoder.bytes` (thanks @eriktim)

---

Code that shows when it **doesn't work**:
https://ellie-app.com/45kPVqsrmPta1 (see logs)
_Chunks are equal when they shouldn't be._

Code that shows the **decoder actually does work**:
https://ellie-app.com/45mTT24dtvMa1 (see logs)
_Chunks are different, as it should be._

The difference between these examples, is that the first one defines an additional decoder that uses `Decode.loop` (through the `buildChunksDecoder` function).

---

Simplified example:

```elm
-- Decoders to split Bytes in chunks
(decoder512, decoder32) =
    ( buildChunksDecoder (512 // 8)
    , buildChunksDecoder (32 // 8)
    )

-- Create chunks
chunks =
    "61626364656667686263646566676869636465666768696A6465666768696A6B65666768696A6B6C666768696A6B6C6D6768696A6B6C6D6E68696A6B6C6D6E6F696A6B6C6D6E6F706A6B6C6D6E6F70716B6C6D6E6F7071726C6D6E6F707172736D6E6F70717273746E6F70717273747580000000000000000000000000000380"
        |> Hex.toBytes
        |> Maybe.andThen (\bytes -> Decode.decode (decoder512 bytes) bytes)
        |> Maybe.map (List.map (\block -> Decode.decode (decoder32 block) block))
        |> Maybe.andThen Maybe.combine
        |> Maybe.map (List.map (List.map Hex.fromBytes))
         
-- Proof that it doesn't work:
-- THESE SHOULD NOT BE EQUAL
fst = Debug.log "First chunk" (List.getAt 0 chunks)
snd = Debug.log "Second chunk" (List.getAt 1 chunks)



{-| Chunky decoder builder.

    Divides `Bytes` into chunks of x bytes.

-}
buildChunksDecoder : Int -> Bytes -> Decoder (List Bytes)
buildChunksDecoder bytesInChunk bytes =
    Decode.loop
        { chunksLeft = ceiling (toFloat (Bytes.width bytes) / toFloat bytesInChunk)
        , chunks = []
        }
        (\state ->
            if state.chunksLeft <= 0 then
                Decode.succeed (Done state.chunks)

            else
                Decode.map
                    (\chunk ->
                        Loop
                            { chunksLeft = state.chunksLeft - 1
                            , chunks = List.append state.chunks [ chunk ]
                            }
                    )
                    (Decode.bytes bytesInChunk)
        )
```

---

It's a fairly complex issue, so let me know if I need to reduce it further.  
Thanks! ✌️

**Comment by eriktim** [comment]
I am also running into this issue with my ProtoBuf decoder. However, I am not sure it has to do with `Decode.loop`, I _think_ I've seen it with a custom recursion as well.
I tried creating a more basic [example](https://ellie-app.com/46nmGcYyzp3a1) where replacing `Decode.unsignedInt8` with `Decode.bytes 1` causes things to break.

```
-- 10 bytes
data =
    Hex.toBytes "0102030405060708090A"
        |> Maybe.withDefault (Encode.encode <| Encode.sequence [])

-- 2x5 bytes, i.e. ["0102030405","060708090A"]
list =
    data
        |> Decode.decode
            (Decode.bytes 5
                |> Decode.andThen (\a -> Decode.map (\b -> [ a, b ]) (Decode.bytes 5))
            )
        |> Maybe.withDefault []

-- run the decoder for both items
mapped =
    list
        |> List.map (\bs -> Decode.decode (decoder <| Bytes.width bs) bs)
        |> Debug.log "mapped"

-- the loop decoder
decoder w =
    Decode.loop ( w, [] )
        (\( n, result ) ->
            if n <= 0 then
                Decode.succeed <| Decode.Done result

            else
                --Decode.map (\v -> Decode.Loop ( n - 1, v :: result )) Decode.unsignedInt8
                Decode.map (\v -> Decode.Loop ( n - 1, Hex.fromBytes v :: result )) (Decode.bytes 1)
        )
```

For the last two `Decode.map (\v -> Decode.Loop ...` lines, enabling
* `Decode.unsignedInt8` correctly results in `mapped: [Just [5,4,3,2,1],Just [10,9,8,7,6]]`
* `Decode.bytes 1` unfortunately results in `mapped: [Just ["05","04","03","02","01"],Just ["05","04","03","02","01"]]`

Could it have something to do with the fact that `Decode.bytes` "_Copies_ a given number of bytes into a new `Bytes` sequence."?

**Comment by icidasset** [comment]
Nice one @eriktim 👌 I think you're right.

The `bytes` decoder uses this function:
https://github.com/elm/bytes/blob/master/src/Elm/Kernel/Bytes.js#L149
Which uses the buffer from another [DataView](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView), and that buffer __is a reference__.
So if that reference changes, the copy changes as well.
It should be `bytes.buffer.slice()` if I'm not mistaken (see [docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/slice)).

Will test out my theory soon when I have some free time.

**Comment by eriktim** [comment]
Yes, I've been looking into that as well. But the referenced data should not change either, should it?
It looks as if the offset gets reset. When splitting the 10 bytes into 6 and 4 (instead of 5-5) you can see the lengths are correct.

**Comment by eriktim** [comment]
**Expanding the offset parameter on [this line](https://github.com/elm/bytes/blob/1.0.7/src/Elm/Kernel/Bytes.js#L149) to `bytes.byteOffset + offset` (instead of `offset` only) seems to fix the issue.** Both my previous example as my ProtoBuf Decoder run successfully with the change.
I think this is because the `DataView.prototype.getUint8` and friends respect the offset of the original `DataView`, whereas `Bytes.Decode.bytes` currently ignores it. When using `Bytes.Decode.bytes` from the start of a `Bytes` sequence this obviously does not cause any issues.

**Comment by icidasset** [comment]
@eriktim Awesome 🙌  Do you want to create a PR or should I?

**Comment by eriktim** [comment]
I just started doing that ;-)

**Comment by icidasset** [comment]
@eriktim Could you tell me how you tested your fix? 🤔 It doesn't let me run the Elm Kernel code.

**Comment by eriktim** [comment]
Sure @icidasset, I tested it by modifying my `1.0.7` installation:

* Apply the patch in `~/.elm/0.19.0/package/elm/bytes/1.0.7/src/Elm/Kernel/Bytes.js`;
* Remove all `.dat` files in `~/.elm/0.19.0/package/elm/bytes/1.0.7`;
* Run your code.

Afterwards you can just delete the `~/.elm/0.19.0/package/elm/bytes/1.0.7` directory to restore the changes.

**Comment by icidasset** [comment]
Thanks @eriktim ! I'm going to close this issue in favor of #12, where I explained the issue we have in greater detail and made a smaller SSCCE.
